### ISSUE TITLE
Merge the Docs repository with the main Nimble project

### ISSUE THREAD

**Issue by julianstirling** [Wakoma/docs#31]
Currently we have a Nimble repo and a seperate Docs repo for GitBuilding. The docs should really be in the same repo as the source as it breaks many GitBuilding features if they are not.

**Comment by ericnitschke** [comment]
thanks @julianstirling. Wakoma/docs was mainly for the Lokal project.  All nimble docs will be here: https://github.com/Wakoma/nimble/tree/master/doc
